# Docs: <https://git.io/JR5E4>

name: 💡 Feature request
description: Suggest an idea for this project
labels: ['type:feature_request']
assignees: [tarampampam]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: Describe the problem to be solved
      description: Please present a concise description of the problem to be addressed by this feature request
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggest a solution
      description: A concise description of your preferred solution
      placeholder: If there are multiple solutions, please present each one separately

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the feature request
      placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in
