// Code generated by go:generate. DO NOT EDIT.

package templates

import _ "embed"

// Template content is loaded from the corresponding HTML files at compile time via go:embed.
var (
	//go:embed html/app-down.tpl.html
	HTMLTemplateAppDown string

	//go:embed html/cats.tpl.html
	HTMLTemplateCats string

	//go:embed html/connection.tpl.html
	HTMLTemplateConnection string

	//go:embed html/ghost.tpl.html
	HTMLTemplateGhost string

	//go:embed html/hacker-terminal.tpl.html
	HTMLTemplateHackerTerminal string

	//go:embed html/l7.tpl.html
	HTMLTemplateL7 string

	//go:embed html/lost-in-space.tpl.html
	HTMLTemplateLostInSpace string

	//go:embed html/noise.tpl.html
	HTMLTemplateNoise string

	//go:embed html/orient.tpl.html
	HTMLTemplateOrient string

	//go:embed html/shuffle.tpl.html
	HTMLTemplateShuffle string

	//go:embed html/win98.tpl.html
	HTMLTemplateWin98 string
)

// HTMLTemplateName* constants hold the canonical name of each built-in HTML template (filename without extension).
const (
	HTMLTemplateNameAppDown        = "app-down"
	HTMLTemplateNameCats           = "cats"
	HTMLTemplateNameConnection     = "connection"
	HTMLTemplateNameGhost          = "ghost"
	HTMLTemplateNameHackerTerminal = "hacker-terminal"
	HTMLTemplateNameL7             = "l7"
	HTMLTemplateNameLostInSpace    = "lost-in-space"
	HTMLTemplateNameNoise          = "noise"
	HTMLTemplateNameOrient         = "orient"
	HTMLTemplateNameShuffle        = "shuffle"
	HTMLTemplateNameWin98          = "win98"
)

// BuiltInHTML returns a new map of all built-in HTML templates keyed by their canonical name.
// The map itself is freshly allocated on each call, so adding or removing keys is safe.
func BuiltInHTML() map[string]string {
	return map[string]string{
		HTMLTemplateNameAppDown:        HTMLTemplateAppDown,
		HTMLTemplateNameCats:           HTMLTemplateCats,
		HTMLTemplateNameConnection:     HTMLTemplateConnection,
		HTMLTemplateNameGhost:          HTMLTemplateGhost,
		HTMLTemplateNameHackerTerminal: HTMLTemplateHackerTerminal,
		HTMLTemplateNameL7:             HTMLTemplateL7,
		HTMLTemplateNameLostInSpace:    HTMLTemplateLostInSpace,
		HTMLTemplateNameNoise:          HTMLTemplateNoise,
		HTMLTemplateNameOrient:         HTMLTemplateOrient,
		HTMLTemplateNameShuffle:        HTMLTemplateShuffle,
		HTMLTemplateNameWin98:          HTMLTemplateWin98,
	}
}
