name: dependabot

on:
  pull_request: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot: # https://tinyurl.com/e69djmen
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: metadata
        with: {github-token: "${{ secrets.GITHUB_TOKEN }}"}

      - name: Enable auto-merge for Dependabot PRs
        if: ${{ contains(fromJSON('["version-update:semver-minor", "version-update:semver-patch"]'), steps.metadata.outputs.update-type) }}
        run: gh pr merge --auto --merge "$PR_URL"
        continue-on-error: true
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
